In [2]:
import pandas as pd 
import os

In [7]:
os.getcwd()

'c:\\Users\\LENOVO\\Desktop\\Docker-Compose-Tuto'

In [6]:
os.chdir("..")
os.getcwd()

'c:\\Users\\LENOVO\\Desktop\\Docker-Compose-Tuto'

In [8]:
df = pd.read_csv("Data/evaluate/cancer_eval.csv")

In [9]:
df.head(5)

,diagnosis,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst
0,M,27.0300,21.28,133.10,1911.5,0.1229,0.2326,0.4808,0.1712,0.3098,0.0890
1,B,9.8339,16.83,71.10,485.0,0.1294,0.2480,0.1028,0.0604,0.3042,0.0647
2,B,13.5000,22.06,63.75,238.2,0.1368,0.2409,0.2389,0.0949,0.2701,0.0699
3,M,18.4700,23.27,138.20,2132.6,0.1765,0.3863,0.3261,0.1461,0.3636,0.0942
4,B,10.6200,18.60,79.23,399.4,0.1435,0.1530,0.1174,0.1161,0.2434,0.0580

In [10]:
df.describe()

,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst
count,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,16.231420,20.259400,108.989100,927.74100,0.137690,0.260795,0.277961,0.135144,0.294551,0.082874
std,5.578287,3.332993,34.574831,546.84728,0.018706,0.112449,0.156432,0.058775,0.046411,0.013312
min,7.000000,13.910000,50.000000,200.00000,0.090000,0.070000,0.020000,0.020000,0.184900,0.058000
25%,11.452500,17.855000,79.015000,463.45000,0.123650,0.182175,0.137650,0.088075,0.265975,0.074475
50%,15.035000,20.015000,101.100000,722.30000,0.138400,0.235900,0.251700,0.128800,0.295000,0.081250
75%,21.110000,22.895000,138.800000,1469.00000,0.149400,0.316375,0.424150,0.185500,0.325250,0.090425
max,28.500000,27.730000,178.300000,2132.60000,0.187600,0.600000,0.650000,0.252800,0.440700,0.126000